server:
  port: 8085

spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/permission?useUnicode=true&&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    url: jdbc:mysql://127.0.0.1:3306/permission?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  main:
    allow-bean-definition-overriding: true


  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    root: debug

#mybatis-plus:
#  mapper-locations: classpath*:resources/mappers/*.xml
#  configuration:
#    aggressive-lazy-loading: false
#  global-config:
#    db-config:
#      logic-delete-value: 1

